### ISSUE TITLE
xklb 2.2.107 works but 2.2.110 fails — 'lb tubeadd <db> <url>' returns 'sqlite3.OperationalError: no such table: playlists'

### ISSUE THREAD

**Issue by holta** [chapmanjacobd/library#19]
**Describe the bug**

xklb 2.2.107 works but 2.2.110 fails — `lb tubeadd <db> <url>` returns `sqlite3.OperationalError: no such table: playlists`

**To Reproduce**

Example error below; Thanks @chapmanjacobd for taking a look!

```
lb tubeadd panama5.db https://youtu.be/6GI0zANA3S4
Importing playlist-less media https://youtu.be/6GI0zANA3S4
Traceback (most recent call last):
  File "/home/iiab-admin/.local/lib/python3.10/site-packages/xklb/playlists.py", line 136, in decrease_update_delay
    args.db.conn.execute(
sqlite3.OperationalError: no such table: playlists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/iiab-admin/.local/bin/lb", line 8, in <module>
    sys.exit(library())
  File "/home/iiab-admin/.local/lib/python3.10/site-packages/xklb/lb.py", line 311, in library
    args.func()
  File "/home/iiab-admin/.local/lib/python3.10/site-packages/xklb/tube_extract.py", line 109, in tube_add
    tube_backend.get_playlist_metadata(args, path, tube_backend.tube_opts(args))
  File "/home/iiab-admin/.local/lib/python3.10/site-packages/xklb/tube_backend.py", line 174, in get_playlist_metadata
    playlists.decrease_update_delay(args, playlist_path)
  File "/home/iiab-admin/.local/lib/python3.10/site-packages/xklb/playlists.py", line 152, in decrease_update_delay
    args.db.conn.execute("ALTER TABLE playlists ADD COLUMN hours_update_delay INTEGER DEFAULT 70")
sqlite3.OperationalError: no such table: playlists
```

**Expected behavior**

Eliminating xklb 2.2.110 regression, so things presumably work like 2.2.107 😅

**Additional context**

Ubuntu 22.04.3 LTS

```
$ uname -a
Linux lrn2 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ python3 --version
Python 3.10.12
```

**Comment by chapmanjacobd** [comment]
thanks for opening this ticket and providing the stack trace!

I've fixed this regression in v2.2.111 which will be released in a few minutes
